// import { Fredoka_One, Baloo_2, Poppins, Quicksand } from "next/font/google";
"use client";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { useState } from "react";
import Confetti from "react-confetti";

// const fredokaOne = Fredoka_One({
//   variable: "--font-fredoka",
//   subsets: ["latin"],
// });

// const baloo2 = Baloo_2({
//   variable: "--font-baloo2",
//   subsets: ["latin"],
// });

// const poppins = Poppins({
//   variable: "--font-poppins",
//   subsets: ["latin"],
// });

// const quicksand = Quicksand({
//   variable: "--font-quicksand",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [confettiActive, setConfettiActive] = useState(false);

  const triggerConfetti = () => {
    setConfettiActive(true);
    setTimeout(() => setConfettiActive(false), 3000); // 3-second burst
  };

  return (
    <html lang="en">
      <body
      // className={`${fredokaOne.variable} ${baloo2.variable} ${poppins.variable} ${quicksand.variable} antialiased`}
      >
        <Navbar triggerConfetti={triggerConfetti} />
        {children}
        {confettiActive && (
          <Confetti
            width={window.innerWidth}
            height={window.innerHeight}
            numberOfPieces={500}
            recycle={false}
            gravity={0.3}
          />
        )}
      </body>
    </html>
  );
}
